name: nonogram
description: A Flutter application for solving and playing Nonogram puzzles.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_linter: ^3.0.0

flutter:
  uses-material-design: true
